package CC;


import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WXU
 */
public class CCJAppletForm extends javax.swing.JApplet {

    /**
     * Initializes the applet CCJAppletForm
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CCJAppletForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CCJAppletForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CCJAppletForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CCJAppletForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        coronajLabel.setVisible(false);
        coronajTextField.setVisible(false);
        jLabel5.setVisible(false);
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanel = new javax.swing.JPanel();
        pressurejTextField = new javax.swing.JTextField();
        driftVjTextField = new javax.swing.JTextField();
        coronajTextField = new javax.swing.JTextField();
        sigIntensityjTextField = new javax.swing.JTextField();
        tempjTextField = new javax.swing.JTextField();
        rItensityjTextField = new javax.swing.JTextField();
        reagentjComboBox = new javax.swing.JComboBox();
        reagentionjLabel = new javax.swing.JLabel();
        pressurejLabel = new javax.swing.JLabel();
        driftjLabel = new javax.swing.JLabel();
        coronajLabel = new javax.swing.JLabel();
        rIntensityjLabel = new javax.swing.JLabel();
        sIntensityjLabel = new javax.swing.JLabel();
        tempjLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        outputPanel = new javax.swing.JPanel();
        concjTextField = new javax.swing.JTextField();
        enratiojTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inputjLabel = new javax.swing.JLabel();
        outputjLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        inputPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pressurejTextField.setText("0");

        driftVjTextField.setText("0");

        coronajTextField.setText("0");

        sigIntensityjTextField.setText("0");

        tempjTextField.setText("0");

        rItensityjTextField.setText("0");

        reagentjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO3-(HNO3)", "CO3-/CO4-", "H3O+" }));
        reagentjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reagentjComboBoxActionPerformed(evt);
            }
        });

        reagentionjLabel.setText("Reagent Ion");

        pressurejLabel.setText("Drift tube pressure");

        driftjLabel.setText("Drift tube Voltage");

        coronajLabel.setText("Corona discharge Voltage");

        rIntensityjLabel.setText("Reagent ion intensity");

        sIntensityjLabel.setText("Signal Intensity");

        tempjLabel.setText("mixing zone temperature");

        jLabel3.setText("torr");

        jLabel4.setText("V");

        jLabel5.setText("V");

        jLabel6.setText("Mcps");

        jLabel7.setText("cps");

        jLabel8.setText("Celsius");

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reagentionjLabel)
                    .addComponent(pressurejLabel)
                    .addComponent(driftjLabel)
                    .addComponent(coronajLabel)
                    .addComponent(rIntensityjLabel)
                    .addComponent(sIntensityjLabel)
                    .addComponent(tempjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(pressurejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(sigIntensityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(tempjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(rItensityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(reagentjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(inputPanelLayout.createSequentialGroup()
                            .addComponent(driftVjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(inputPanelLayout.createSequentialGroup()
                            .addComponent(coronajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reagentionjLabel)
                    .addComponent(reagentjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pressurejLabel)
                            .addComponent(pressurejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(driftjLabel)
                        .addGap(12, 12, 12))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(driftVjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coronajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coronajLabel)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sigIntensityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rIntensityjLabel)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sIntensityjLabel)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rItensityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempjLabel)
                    .addComponent(jLabel8)))
        );

        outputPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        concjTextField.setText("0");

        enratiojTextField.setText("0");

        jLabel1.setText("Concentration");

        jLabel2.setText("E/N ratio");

        jLabel9.setText("ppt");

        jLabel10.setText("Td");

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(133, 133, 133)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addComponent(enratiojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addComponent(concjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enratiojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)))
        );

        inputjLabel.setText("Input Parameters");

        outputjLabel.setText("outputs");

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputjLabel)
                            .addComponent(outputjLabel)
                            .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jButton1)
                        .addGap(61, 61, 61)
                        .addComponent(jButton2)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reagentjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reagentjComboBoxActionPerformed
        // TODO add your handling code here:
        JComboBox comboList=(JComboBox) evt.getSource();
        if(comboList.getSelectedItem()=="NO3-(HNO3)"||comboList.getSelectedItem()=="CO3-/CO4-") {
            coronajLabel.setVisible(false);
            coronajTextField.setVisible(false);
            jLabel5.setVisible(false);
            driftjLabel.setVisible(true);
            driftVjTextField.setVisible(true);
            jLabel4.setVisible(true);
            
        }
        else {
            driftjLabel.setVisible(false);
            driftVjTextField.setVisible(false);
            jLabel4.setVisible(false);
            coronajLabel.setVisible(true);
            coronajTextField.setVisible(true);
            jLabel5.setVisible(true);
        }
    }//GEN-LAST:event_reagentjComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        concjTextField.setText("0");
        coronajTextField.setText("0");
        driftVjTextField.setText("0");
        enratiojTextField.setText("0");
        pressurejTextField.setText("0");
        rItensityjTextField.setText("0");
        sigIntensityjTextField.setText("0");
        tempjTextField.setText("0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double driftV = Double.parseDouble(driftVjTextField.getText());
        double coronaV = Double.parseDouble(coronajTextField.getText());
        double pressure = Double.parseDouble(pressurejTextField.getText());
        double rI = Double.parseDouble(rItensityjTextField.getText());
        double sI = Double.parseDouble(sigIntensityjTextField.getText());
        double temp = Double.parseDouble(tempjTextField.getText());
        double conc,enratio;
        double krateConst,driftTime,mobility,voltage;
        double driftVelocity, flowVelocity, ElecField, flow, totalVelocity;
        if(reagentjComboBox.getSelectedItem()=="NO3-(HNO3)") {
            krateConst = 2.0E-9;
            mobility = 1.88;
            voltage = driftV;
            flow = 2040.0;
        }
        else if(reagentjComboBox.getSelectedItem()=="CO3-/CO4-") {
            krateConst = 2.0E-9;
            mobility = 1.88;
            voltage = driftV;
            flow = 2040.0;
        }
        else {
            krateConst = 2.0E-9;
            mobility = 2.8;
            voltage = coronaV * 14.0 / (14.0 + 2.0);
            flow = 2320.0;
        }
        mobility = mobility * 765 / pressure * 295 / 300;
        ElecField = voltage / 14.0;
        driftVelocity = ElecField * mobility;
        flowVelocity = flow * 765/ pressure * 295 / 298 / (3.1415926 * 1.4 * 1.4) / 60.0;
        totalVelocity = driftVelocity + flowVelocity;
        driftTime = 14.0 / totalVelocity;
        conc = sI / rI / 1000000.0/ driftTime / krateConst;
        conc = conc * 765 / pressure * 295 / (temp + 273.15);
        conc = conc / (2.47E19 * 273.15 / (273.15 + temp)) * 1E12;
        enratio = ElecField / (2.47E19 * 273.15 / (273.15+ temp) * pressure/ 765.0) *1E17;
        concjTextField.setText(Double.toString(conc));
        enratiojTextField.setText(Double.toString(enratio));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField concjTextField;
    private javax.swing.JLabel coronajLabel;
    private javax.swing.JTextField coronajTextField;
    private javax.swing.JTextField driftVjTextField;
    private javax.swing.JLabel driftjLabel;
    private javax.swing.JTextField enratiojTextField;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel inputjLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JLabel outputjLabel;
    private javax.swing.JLabel pressurejLabel;
    private javax.swing.JTextField pressurejTextField;
    private javax.swing.JLabel rIntensityjLabel;
    private javax.swing.JTextField rItensityjTextField;
    private javax.swing.JLabel reagentionjLabel;
    private javax.swing.JComboBox reagentjComboBox;
    private javax.swing.JLabel sIntensityjLabel;
    private javax.swing.JTextField sigIntensityjTextField;
    private javax.swing.JLabel tempjLabel;
    private javax.swing.JTextField tempjTextField;
    // End of variables declaration//GEN-END:variables
}
